# Generated by Django 3.2 on 2021-06-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_alter_userpost_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleuser',
            name='email',
        ),
    ]
